// === WinAPI Imports ===
DECLSPEC_IMPORT HINTERNET WINAPI WININET$InternetOpenW(LPCWSTR, DWORD, LPCWSTR, LPCWSTR, DWORD);
DECLSPEC_IMPORT HINTERNET WINAPI WININET$InternetConnectW(HINTERNET, LPCWSTR, INTERNET_PORT, LPCWSTR, LPCWSTR, DWORD, DWORD, DWORD_PTR);
DECLSPEC_IMPORT HINTERNET WINAPI WININET$HttpOpenRequestW(HINTERNET, LPCWSTR, LPCWSTR, LPCWSTR, LPCWSTR, LPCWSTR*, DWORD, DWORD_PTR);
DECLSPEC_IMPORT BOOL WINAPI WININET$HttpSendRequestW(HINTERNET, LPCWSTR, DWORD, LPVOID, DWORD);
DECLSPEC_IMPORT BOOL WINAPI WININET$HttpQueryInfoW(HINTERNET, DWORD, LPVOID, LPDWORD, LPDWORD);
DECLSPEC_IMPORT BOOL WINAPI WININET$InternetCloseHandle(HINTERNET);
DECLSPEC_IMPORT DWORD WINAPI KERNEL32$GetLastError(void);